name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
          registry-url: "https://registry.npmjs.org/"

      - name: Install pnpm
        run: corepack enable && pnpm install --frozen-lockfile

      - name: Build Next.js project
        run: pnpm run build && pnpm run export

      - name: Setup GitHub Pages
        run: |
          touch out/.nojekyll  # Prevent GitHub Pages from treating _next as a Jekyll folder

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: out
